export type ClaimRisk = "low" | "medium" | "high" | "critical";

export type ClaimEvidenceStatus =
  | "verified"
  | "conditional"
  | "unverified"
  | "blocked"
  | "expired"
  | "rejected";

export type ClaimPublicationAction = "allow" | "qualify" | "block";

export interface PublicClaim {
  id: string;
  route: string;
  sourcePath: string;
  section: string;
  category:
    | "availability"
    | "performance"
    | "security"
    | "staffing"
    | "identity"
    | "relationship"
    | "regulatory"
    | "privacy"
    | "product"
    | "preview";
  risk: ClaimRisk;
  evidenceStatus: ClaimEvidenceStatus;
  publicationAction: ClaimPublicationAction;
  currentWording: string;
  approvedWording: string;
  evidenceRequired: readonly string[];
  owner: string;
  reviewBy: string;
  notes?: string;
}

export const priorityClaimRoutes = [
  "/hub",
  "/services",
  "/company",
  "/request-access",
  "/get-started",
  "/trust-center",
  "/store",
  "/community-hub",
] as const;

export const publicClaims = [
  {
    id: "HUB-001",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "Command Center",
    category: "availability",
    risk: "critical",
    evidenceStatus: "blocked",
    publicationAction: "block",
    currentWording: "Threat Command — Active / Compliance Center — Live",
    approvedWording:
      "Capabilities are available only when configured in an approved client workspace and confirmed in the signed scope.",
    evidenceRequired: ["production feature verification", "workspace entitlement record", "approved service scope"],
    owner: "Product Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-002",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "SOC Capabilities",
    category: "availability",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "24/7 Global Coverage across North America, EMEA, and Asia-Pacific",
    approvedWording: "Coverage hours and regional support are defined in the signed service scope.",
    evidenceRequired: ["staffing roster", "shift schedule", "regional coverage evidence", "provider agreement"],
    owner: "Security Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-003",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "SOC Capabilities",
    category: "performance",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Documented mean time to acknowledge of 6 minutes across all severity levels",
    approvedWording: "Response and acknowledgement targets are documented in the applicable service agreement.",
    evidenceRequired: ["incident timestamps", "measurement period", "sample size", "calculation method", "approved SLA"],
    owner: "Security Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-004",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "SOC Capabilities",
    category: "security",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Incident-response playbooks are executed automatically upon alert confirmation",
    approvedWording: "Approved playbooks may be coordinated after scope, validation, and human authorization.",
    evidenceRequired: ["playbook inventory", "automation controls", "approval policy", "test evidence"],
    owner: "Security Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-005",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "SOC Capabilities",
    category: "staffing",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Staffed by certified analysts operating at enterprise scale",
    approvedWording: "Staffing qualifications are confirmed for each approved engagement.",
    evidenceRequired: ["current roster", "role verification", "certificate verification", "publication consent"],
    owner: "People Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-006",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "Support Access",
    category: "availability",
    risk: "high",
    evidenceStatus: "conditional",
    publicationAction: "qualify",
    currentWording: "24/7 direct line for active incidents and critical security events",
    approvedWording: "Incident escalation channels and operating hours are defined by engagement.",
    evidenceRequired: ["call-routing evidence", "coverage schedule", "escalation policy", "approved SLA"],
    owner: "Client Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-007",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "Support Access",
    category: "security",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Encrypted in-platform messaging with a dedicated account manager and SOC team",
    approvedWording:
      "Protected messaging is available only after the relevant access, transport, storage, and retention controls are activated and verified.",
    evidenceRequired: ["encryption architecture", "access-control test", "retention policy", "production activation evidence"],
    owner: "Platform Security",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-008",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "Support Access",
    category: "performance",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Email support response in less than four hours",
    approvedWording: "Support response targets are defined by the applicable service agreement.",
    evidenceRequired: ["support policy", "ticket data", "measurement period", "approved SLA"],
    owner: "Client Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "HUB-009",
    route: "/hub",
    sourcePath: "src/app/hub/page.tsx",
    section: "Service Requests",
    category: "performance",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "A dedicated account manager will acknowledge within two hours",
    approvedWording: "Acknowledgement targets are defined by the applicable service agreement.",
    evidenceRequired: ["account-management model", "ticket evidence", "coverage hours", "approved SLA"],
    owner: "Client Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-001",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Executive Board",
    category: "identity",
    risk: "critical",
    evidenceStatus: "blocked",
    publicationAction: "block",
    currentWording: "Named executive profiles, titles, biographies, qualifications, and prior employment histories",
    approvedWording:
      "Public leadership profiles are published only after identity, title, biography, credential, and consent verification.",
    evidenceRequired: ["identity verification", "role confirmation", "biography evidence", "credential evidence", "publication consent"],
    owner: "Executive Office",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-002",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Team Divisions",
    category: "staffing",
    risk: "critical",
    evidenceStatus: "blocked",
    publicationAction: "block",
    currentWording: "Specific team headcounts across six divisions",
    approvedWording: "Team composition and staffing are confirmed for each approved engagement.",
    evidenceRequired: ["current roster", "employment or contractor status", "role mapping", "publication approval"],
    owner: "People Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-003",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Cybersecurity Division",
    category: "availability",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "24/7 operational coverage across all client environments",
    approvedWording: "Coverage is defined by the approved engagement, staffing plan, and service agreement.",
    evidenceRequired: ["staffing plan", "coverage schedule", "client-scope evidence", "provider evidence"],
    owner: "Security Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-004",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Real Estate Division",
    category: "product",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Integrations with major county recorder databases for real-time deed monitoring",
    approvedWording:
      "Property-record monitoring depends on verified jurisdictional sources, provider capability, authorization, and an approved service scope.",
    evidenceRequired: ["provider contract", "integration test", "jurisdiction list", "data-source authorization"],
    owner: "Real Estate Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-005",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Partners & Trustees",
    category: "relationship",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Named memberships, affiliations, participation, and partnerships with industry organizations",
    approvedWording:
      "Association, provider, and partner relationships are described publicly only when the relationship and wording are verified and authorized.",
    evidenceRequired: ["current agreement or membership", "effective dates", "logo or name permission", "approved relationship wording"],
    owner: "Executive Office",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-006",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Company Values",
    category: "relationship",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "qualify",
    currentWording: "GEM Enterprise is not a reseller or affiliate of any technology vendor",
    approvedWording:
      "Commercial, referral, reseller, affiliate, and provider relationships are disclosed where they are relevant to an approved recommendation or engagement.",
    evidenceRequired: ["vendor register", "commercial relationship review", "conflict-of-interest policy"],
    owner: "Compliance",
    reviewBy: "2026-07-31",
  },
  {
    id: "COMPANY-007",
    route: "/company",
    sourcePath: "src/app/company/page.tsx",
    section: "Compliance & Regulatory Disclosure",
    category: "regulatory",
    risk: "critical",
    evidenceStatus: "conditional",
    publicationAction: "qualify",
    currentWording: "GEM Enterprise operates under applicable federal and state regulations",
    approvedWording:
      "Services are structured subject to applicable law, jurisdiction, eligibility, and engagement-specific compliance requirements; no licence or regulatory status is implied unless separately identified and evidenced.",
    evidenceRequired: ["entity registrations", "licence analysis", "jurisdiction matrix", "legal review"],
    owner: "Compliance",
    reviewBy: "2026-07-31",
  },
  {
    id: "REQUEST-001",
    route: "/request-access",
    sourcePath: "src/app/request-access/page.tsx",
    section: "Hero",
    category: "preview",
    risk: "high",
    evidenceStatus: "blocked",
    publicationAction: "block",
    currentWording: "A vetted, invitation-only network of operators, investors, and advisors",
    approvedWording: "Submit a non-binding request for qualification and human review.",
    evidenceRequired: ["production community approval", "membership operating model", "current member evidence", "publication approval"],
    owner: "Community Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "REQUEST-002",
    route: "/request-access",
    sourcePath: "src/app/request-access/page.tsx",
    section: "Application Principles",
    category: "privacy",
    risk: "critical",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "Applications, profiles, and activity are private and member lists are never shared with third parties",
    approvedWording:
      "Personal information is handled according to the published privacy notice, approved access controls, retention rules, and applicable service providers.",
    evidenceRequired: ["privacy notice", "data-flow map", "processor register", "retention policy", "access-control test"],
    owner: "Privacy",
    reviewBy: "2026-07-31",
  },
  {
    id: "REQUEST-003",
    route: "/request-access",
    sourcePath: "src/app/request-access/page.tsx",
    section: "Application Principles",
    category: "performance",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "A respectful decision notice within 10 business days",
    approvedWording: "Review timing depends on request type, evidence, jurisdiction, staffing, and required checks.",
    evidenceRequired: ["review policy", "case timestamps", "staffing model", "approved service target"],
    owner: "Client Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "REQUEST-004",
    route: "/request-access",
    sourcePath: "src/app/request-access/page.tsx",
    section: "Hero",
    category: "performance",
    risk: "high",
    evidenceStatus: "unverified",
    publicationAction: "block",
    currentWording: "We respond to every submission",
    approvedWording: "Each submission is recorded for review; response timing and outcome are not guaranteed by the public form.",
    evidenceRequired: ["durable intake record", "queue monitoring", "case-closure evidence", "approved response policy"],
    owner: "Client Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "GETSTARTED-001",
    route: "/get-started",
    sourcePath: "src/app/get-started/page.tsx",
    section: "Onboarding Model",
    category: "availability",
    risk: "high",
    evidenceStatus: "conditional",
    publicationAction: "qualify",
    currentWording: "Applicants move through KYC, compliance review, entitlement approval, and protected portal access",
    approvedWording:
      "Applicable verification, review, and portal steps depend on applicant type, configured controls, provider availability, and human approval.",
    evidenceRequired: ["route test", "provider status", "review workflow", "entitlement test"],
    owner: "Client Operations",
    reviewBy: "2026-07-31",
  },
  {
    id: "TRUST-001",
    route: "/trust-center",
    sourcePath: "src/app/trust-center/page.tsx",
    section: "Core Controls",
    category: "security",
    risk: "high",
    evidenceStatus: "conditional",
    publicationAction: "qualify",
    currentWording: "RBAC, encrypted transport, secure cookies, rate limiting, audit logging, KYC gating, and human review",
    approvedWording:
      "Control statements describe implemented or designed controls and must be supported by current code, configuration, tests, and operational evidence; they do not imply certification.",
    evidenceRequired: ["code references", "configuration evidence", "test results", "operational procedure"],
    owner: "Platform Security",
    reviewBy: "2026-07-31",
  },
  {
    id: "STORE-001",
    route: "/store",
    sourcePath: "src/app/store/page.tsx",
    section: "Request-only Catalogue",
    category: "product",
    risk: "medium",
    evidenceStatus: "verified",
    publicationAction: "allow",
    currentWording: "Catalogue entries are proposed and require written confirmation before acceptance or activation",
    approvedWording: "Catalogue entries are proposed and require written confirmation before acceptance or activation.",
    evidenceRequired: ["storefront source review", "request-only workflow test"],
    owner: "Commerce Operations",
    reviewBy: "2026-08-31",
  },
  {
    id: "SERVICES-001",
    route: "/services",
    sourcePath: "src/app/services/page.tsx",
    section: "Service Activation",
    category: "availability",
    risk: "medium",
    evidenceStatus: "verified",
    publicationAction: "allow",
    currentWording: "Services require confirmed scope, eligibility, staffing, provider, jurisdiction, security, and contractual requirements",
    approvedWording: "Services require confirmed scope, eligibility, staffing, provider, jurisdiction, security, and contractual requirements.",
    evidenceRequired: ["service-page source review", "scope disclaimer test"],
    owner: "Service Operations",
    reviewBy: "2026-08-31",
  },
  {
    id: "COMMUNITY-001",
    route: "/community-hub",
    sourcePath: "src/app/community-hub/page.tsx",
    section: "Controlled Preview",
    category: "preview",
    risk: "medium",
    evidenceStatus: "verified",
    publicationAction: "allow",
    currentWording: "Fictional interface preview with no live members, opportunities, events, secure messaging, or verified network",
    approvedWording: "Fictional interface preview with no live production network represented.",
    evidenceRequired: ["preview disclosure test", "noindex metadata test"],
    owner: "Community Operations",
    reviewBy: "2026-08-31",
  },
] as const satisfies readonly PublicClaim[];

export function claimsForRoute(route: string): readonly PublicClaim[] {
  return publicClaims.filter((claim) => claim.route === route);
}
