export type StorefrontSlug =
  | "main"
  | "campaign-hub"
  | "tiktok"
  | "shopify"
  | "google"
  | "wix"
  | "facebook";

export type StorefrontProduct = {
  id: string;
  sku: string;
  name: string;
  shortDescription: string;
  category: string;
  price: number;
  originalPrice?: number;
  deliveryType: "Physical" | "Digital" | "Service";
  stockLabel: "In Stock" | "Available" | "Request access";
  storefronts: StorefrontSlug[];
  accent: "cyan" | "green" | "purple" | "orange" | "pink";
  image?: string;
  checkoutUrl?: string;
};

export type StorefrontDefinition = {
  slug: StorefrontSlug;
  name: string;
  shortName: string;
  eyebrow: string;
  title: string;
  description: string;
  status: "Live" | "Connected" | "Prepared" | "Pending connection";
  externalUrl?: string;
  externalLabel?: string;
  categories: string[];
};

export const storefrontDefinitions: StorefrontDefinition[] = [
  {
    slug: "main",
    name: "GEM Main Store",
    shortName: "Main Store",
    eyebrow: "Professional product catalog",
    title: "The complete GEM Enterprise service and software store",
    description:
      "Browse 36 professional cybersecurity, financial protection, real estate security, and home safety products — all delivered digitally or as managed services.",
    status: "Live",
    categories: [
      "All",
      "Monitoring Plans",
      "Financial Protection",
      "Home Security",
      "Real Estate Services",
      "Cybersecurity Software",
    ],
  },
  {
    slug: "campaign-hub",
    name: "Campaign Hub",
    shortName: "Campaign Hub",
    eyebrow: "Campaign-ready products",
    title: "Campaign-ready security products and digital offers",
    description:
      "A dedicated page for promoted cybersecurity products, awareness tools, and lead-generation services optimized for social campaigns.",
    status: "Connected",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Financial Protection", "Security Awareness"],
  },
  {
    slug: "tiktok",
    name: "TikTok Shop",
    shortName: "TikTok Shop",
    eyebrow: "Social-commerce catalog",
    title: "Shop GEM products on TikTok",
    description:
      "Browse consumer-friendly cybersecurity and real estate security products here, then visit our official TikTok Shop to complete your purchase.",
    status: "Connected",
    externalUrl: "https://vt.tiktok.com/ZTB58S7Nr/",
    externalLabel: "Open TikTok Shop",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Home Security"],
  },
  {
    slug: "shopify",
    name: "Shopify Store",
    shortName: "Shopify",
    eyebrow: "Connected checkout",
    title: "GEM products on Shopify",
    description:
      "Our Shopify storefront is being transitioned. Browse products here and visit our Wix operational hub for all current purchases and bookings.",
    status: "Pending connection",
    externalUrl: "https://firmgem.wixsite.com/gem-cybersecurity",
    externalLabel: "Visit Wix Store Instead",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software"],
  },
  {
    slug: "google",
    name: "Google Merchant Store",
    shortName: "Google Store",
    eyebrow: "Merchant feed catalog",
    title: "Google Shopping listings for GEM products",
    description:
      "Products prepared for Google Merchant Center and Google Shopping visibility. Browse the catalog here while we finalize the Google feed connection.",
    status: "Prepared",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Real Estate Services", "Home Security"],
  },
  {
    slug: "wix",
    name: "Wix Store Sync",
    shortName: "Wix Store",
    eyebrow: "Synchronized catalog",
    title: "Shop GEM products on Wix",
    description:
      "All 36 professional products synchronized from the Wix operational hub — cybersecurity monitoring, financial protection, home security, real estate services, and cybersecurity software. Visit the live Wix store to purchase.",
    status: "Connected",
    externalUrl: "https://firmgem.wixsite.com/gem-cybersecurity",
    externalLabel: "Open Wix Store",
    categories: ["All", "Monitoring Plans", "Financial Protection", "Home Security", "Real Estate Services", "Cybersecurity Software"],
  },
  {
    slug: "facebook",
    name: "Facebook Store",
    shortName: "Facebook Shop",
    eyebrow: "Social-commerce catalog",
    title: "Shop GEM products on Facebook",
    description:
      "Browse our cybersecurity and real estate security products here, then visit our Facebook page to explore our shop and service offerings.",
    status: "Connected",
    externalUrl: "https://facebook.com/gemcyberassist",
    externalLabel: "Open Facebook Page",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Home Security"],
  },
];

// Image URLs from generated branded product cards
const IMG = {
  familyProtection: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/50068119f_generated_image.png",
  enterpriseShield: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/af1e3f484_generated_image.png",
  businessMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/0fcfdbdd1_generated_image.png",
  proMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/fa5a68144_generated_image.png",
  basicMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7b1af6854_generated_image.png",
  creditFreeze: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/f01c388d9_generated_image.png",
  fraudMasterclass: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/1a8d2dd66_generated_image.png",
  becProtection: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/9e9dbd58c_generated_image.png",
  cryptoWallet: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/67a2937eb_generated_image.png",
  identityShield: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7d770947e_generated_image.png",
  cyberInsurance: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/c64318ce2_generated_image.png",
  identityTheft: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/0d0d9f9bc_generated_image.png",
  familySafety: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/2624cb60b_generated_image.png",
  wifiHardening: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7fdba25db_generated_image.png",
  smartHome: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/697f0c794_generated_image.png",
  homeBuyerFraud: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/abcc3e97d_generated_image.png",
  rentalManagement: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/32d524d6f_generated_image.png",
  investmentConsult: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/644a6e594_generated_image.png",
  dueDiligence: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/a89e712c7_generated_image.png",
  titleFraud: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/cc2e1ee62_generated_image.png",
  darkwebMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/0b866cf74_generated_image.png",
  endpointArmor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/d5cdc44f9_generated_image.png",
  phishGuard: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/cdfb8e1af_generated_image.png",
  vaultSafe: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7f34b96c6_generated_image.png",
  threatShield: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/83a890ee0_generated_image.png",
};

export const storefrontProducts: StorefrontProduct[] = [
  // ====== MONITORING PLANS (6) ======
  {
    id: "gem-family-protection",
    sku: "GEM-MP-001",
    name: "GEM Family Protection Plan",
    shortDescription: "Comprehensive family cybersecurity monitoring — dark web scanning, phishing alerts, and identity protection for one household.",
    category: "Monitoring Plans",
    price: 9.99,
    originalPrice: 14.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "cyan",
    image: IMG.familyProtection,
  },
  {
    id: "gem-enterprise-shield",
    sku: "GEM-MP-002",
    name: "GEM Enterprise Shield — Annual",
    shortDescription: "Enterprise-grade 24/7 SOC monitoring, incident response, and threat intelligence for organizations. Annual prepaid subscription.",
    category: "Monitoring Plans",
    price: 799,
    originalPrice: 999,
    deliveryType: "Service",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "cyan",
    image: IMG.enterpriseShield,
  },
  {
    id: "gem-business-monitor",
    sku: "GEM-MP-003",
    name: "GEM Business Monitor — Monthly",
    shortDescription: "Business-grade continuous monitoring with threat alerts, vulnerability scanning, and compliance reporting.",
    category: "Monitoring Plans",
    price: 49,
    originalPrice: 65,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "cyan",
    image: IMG.businessMonitor,
  },
  {
    id: "gem-pro-monitor",
    sku: "GEM-MP-004",
    name: "GEM Pro Monitor — Monthly",
    shortDescription: "Professional-tier monitoring with advanced threat detection, dark web surveillance, and priority alert delivery.",
    category: "Monitoring Plans",
    price: 19.99,
    originalPrice: 29.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "cyan",
    image: IMG.proMonitor,
  },
  {
    id: "gem-basic-monitor",
    sku: "GEM-MP-005",
    name: "GEM Basic Monitor — Monthly",
    shortDescription: "Entry-level cybersecurity monitoring with weekly threat summaries and basic dark web exposure checks.",
    category: "Monitoring Plans",
    price: 9.99,
    originalPrice: 14.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "cyan",
    image: IMG.basicMonitor,
  },
  {
    id: "gem-threat-alert-sms",
    sku: "GEM-MP-006",
    name: "GEM Basic Threat Alert SMS",
    shortDescription: "Real-time SMS security alerts for defined business and personal monitoring needs. Immediate notification on critical threats.",
    category: "Monitoring Plans",
    price: 10,
    originalPrice: 15,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "cyan",
  },

  // ====== FINANCIAL PROTECTION (5) ======
  {
    id: "gem-identity-theft-shield",
    sku: "GEM-FP-007",
    name: "GEM Identity Theft Shield",
    shortDescription: "Continuous identity theft monitoring with real-time alerts on suspicious account activity and data breaches.",
    category: "Financial Protection",
    price: 7.50,
    originalPrice: 12.50,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "green",
    image: IMG.identityTheft,
  },
  {
    id: "gem-financial-fraud-monitor",
    sku: "GEM-FP-008",
    name: "GEM Financial Fraud Monitor",
    shortDescription: "Financial fraud detection service monitoring bank accounts, credit cards, and investment accounts for unauthorized activity.",
    category: "Financial Protection",
    price: 15,
    originalPrice: 22,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "green",
    image: IMG.identityShield,
  },
  {
    id: "gem-credit-lock-assistant",
    sku: "GEM-FP-009",
    name: "GEM Credit Lock Assistant",
    shortDescription: "Credit monitoring and lock assistance — freeze and unfreeze credit bureau files with guided step-by-step support.",
    category: "Financial Protection",
    price: 9.99,
    originalPrice: 14.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "green",
    image: IMG.creditFreeze,
  },
  {
    id: "gem-investment-scam-detector",
    sku: "GEM-FP-010",
    name: "GEM Investment Scam Detector",
    shortDescription: "AI-powered investment scam detection with alerts on pump-and-dump schemes, phishing brokers, and fraudulent platforms.",
    category: "Financial Protection",
    price: 19.99,
    originalPrice: 29.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "green",
    image: IMG.fraudMasterclass,
  },
  {
    id: "gem-wire-fraud-prevention",
    sku: "GEM-FP-011",
    name: "GEM Wire Fraud Prevention Guide",
    shortDescription: "Comprehensive wire fraud prevention guide with verification protocols for real estate transactions and business payments.",
    category: "Financial Protection",
    price: 29.99,
    originalPrice: 39.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "green",
    image: IMG.becProtection,
  },

  // ====== HOME SECURITY (6) ======
  {
    id: "gem-home-network-scan",
    sku: "GEM-HS-012",
    name: "GEM Home Network Scan",
    shortDescription: "Remote WiFi network security scan identifying open ports, weak encryption, and vulnerable devices on your home network.",
    category: "Home Security",
    price: 35,
    originalPrice: 50,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "purple",
    image: IMG.wifiHardening,
  },
  {
    id: "gem-smart-home-security",
    sku: "GEM-HS-013",
    name: "GEM Smart Home Security Check",
    shortDescription: "Full audit of smart home devices — cameras, locks, thermostats — for known vulnerabilities and default credential exposure.",
    category: "Home Security",
    price: 45,
    originalPrice: 60,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "tiktok", "google", "wix", "facebook"],
    accent: "purple",
    image: IMG.smartHome,
  },
  {
    id: "gem-iot-device-audit",
    sku: "GEM-HS-014",
    name: "GEM IoT Device Audit",
    shortDescription: "IoT device vulnerability assessment covering firmware, network exposure, and data transmission security for all connected devices.",
    category: "Home Security",
    price: 25,
    originalPrice: 35,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "tiktok", "google", "wix"],
    accent: "purple",
  },
  {
    id: "gem-family-cyber-plan",
    sku: "GEM-HS-015",
    name: "GEM Family Cyber Plan",
    shortDescription: "Customized family cybersecurity plan covering all household members — device rules, monitoring setup, and emergency response protocols.",
    category: "Home Security",
    price: 55,
    originalPrice: 75,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "purple",
    image: IMG.familySafety,
  },
  {
    id: "gem-phishing-test",
    sku: "GEM-HS-016",
    name: "GEM Phishing Test & Awareness Report",
    shortDescription: "Simulated phishing test for your household with a detailed awareness report and personalized training recommendations.",
    category: "Home Security",
    price: 15,
    originalPrice: 22,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "purple",
  },
  {
    id: "gem-password-audit",
    sku: "GEM-HS-017",
    name: "GEM Password Strength Audit",
    shortDescription: "Password security audit with recommendations for strengthening credentials across all personal and financial accounts.",
    category: "Home Security",
    price: 10,
    originalPrice: 15,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "tiktok", "google", "wix", "facebook"],
    accent: "purple",
  },

  // ====== REAL ESTATE SERVICES (8) ======
  {
    id: "atr-lease-review",
    sku: "AT-RS-018",
    name: "Alliance Trust — Lease Agreement Review",
    shortDescription: "Legal review and fraud check of lease agreements — identifies suspicious clauses, hidden fees, and potential scam patterns.",
    category: "Real Estate Services",
    price: 45,
    originalPrice: 55,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "atr-title-fraud-check",
    sku: "AT-RS-019",
    name: "Alliance Trust — Title Fraud Check",
    shortDescription: "Title fraud verification service confirming property ownership records and flagging unauthorized title transfers.",
    category: "Real Estate Services",
    price: 35,
    originalPrice: 50,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.titleFraud,
  },
  {
    id: "atr-buyer-cyber-risk",
    sku: "AT-RS-020",
    name: "Alliance Trust — Buyer Cyber Risk Assessment",
    shortDescription: "Cyber risk assessment for property buyers — evaluates wire transfer risks, agent communication security, and document protection.",
    category: "Real Estate Services",
    price: 65,
    originalPrice: 85,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.homeBuyerFraud,
  },
  {
    id: "atr-seller-data-protection",
    sku: "AT-RS-021",
    name: "Alliance Trust — Seller Data Protection Package",
    shortDescription: "Data protection package for property sellers — secures listing information, client documents, and communication channels.",
    category: "Real Estate Services",
    price: 55,
    originalPrice: 70,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "atr-closing-wire-verification",
    sku: "AT-RS-022",
    name: "Alliance Trust — Closing Wire Verification",
    shortDescription: "Wire transfer verification for real estate closings — confirms account authenticity and prevents wire fraud during transactions.",
    category: "Real Estate Services",
    price: 25,
    originalPrice: 35,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "atr-property-listing-audit",
    sku: "AT-RS-023",
    name: "Alliance Trust — Property Listing Cyber Audit",
    shortDescription: "Cybersecurity audit of property listings — checks for scraped content, fake listings, and unauthorized use of property data.",
    category: "Real Estate Services",
    price: 40,
    originalPrice: 55,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "atr-agent-identity-verification",
    sku: "AT-RS-024",
    name: "Alliance Trust — Agent Identity Verification",
    shortDescription: "Real estate agent identity verification — confirms licensing, background, and digital presence to prevent impersonation scams.",
    category: "Real Estate Services",
    price: 20,
    originalPrice: 30,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "atr-client-data-breach-response",
    sku: "AT-RS-025",
    name: "Alliance Trust — Client Data Breach Response Kit",
    shortDescription: "Complete data breach response kit for real estate clients — incident response plan, notification templates, and recovery guidance.",
    category: "Real Estate Services",
    price: 75,
    originalPrice: 100,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },

  // ====== CYBERSECURITY SOFTWARE (11) ======
  {
    id: "gem-endpoint-shield",
    sku: "GEM-CS-026",
    name: "GEM Endpoint Shield — 1 Year Subscription",
    shortDescription: "Annual endpoint security software license — antivirus, ransomware protection, device firewall, and remote wipe for all devices.",
    category: "Cybersecurity Software",
    price: 299,
    originalPrice: 399,
    deliveryType: "Digital",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "pink",
    image: IMG.endpointArmor,
  },
  {
    id: "gem-phishing-defense-toolkit",
    sku: "GEM-CS-027",
    name: "GEM Phishing Defense Toolkit",
    shortDescription: "Complete phishing defense and training toolkit — simulated attacks, awareness modules, and reporting dashboard for teams.",
    category: "Cybersecurity Software",
    price: 199,
    originalPrice: 279,
    deliveryType: "Digital",
    stockLabel: "Request access",
    storefronts: ["main", "campaign-hub", "google", "wix", "facebook"],
    accent: "pink",
    image: IMG.phishGuard,
  },
  {
    id: "gem-compliance-vault",
    sku: "GEM-CS-028",
    name: "GEM Compliance Vault — Annual",
    shortDescription: "Annual compliance management software — document storage, audit trails, policy management, and regulatory tracking.",
    category: "Cybersecurity Software",
    price: 499,
    originalPrice: 699,
    deliveryType: "Digital",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "pink",
    image: IMG.vaultSafe,
  },
  {
    id: "gem-threat-intel-dashboard",
    sku: "GEM-CS-029",
    name: "GEM Threat Intelligence Dashboard",
    shortDescription: "Real-time threat intelligence monitoring dashboard — global threat feeds, CVE tracking, and custom alert configuration.",
    category: "Cybersecurity Software",
    price: 399,
    originalPrice: 549,
    deliveryType: "Digital",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "pink",
    image: IMG.threatShield,
  },
  {
    id: "gem-security-starter-suite",
    sku: "GEM-CS-030",
    name: "GEM Security Starter Suite — Annual",
    shortDescription: "Complete security suite annual license — endpoint protection, phishing defense, compliance vault, and threat dashboard bundled.",
    category: "Cybersecurity Software",
    price: 799,
    originalPrice: 1099,
    deliveryType: "Digital",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "pink",
  },
  {
    id: "gem-vpn-setup-guide",
    sku: "GEM-CS-031",
    name: "GEM VPN Setup & Configuration Guide",
    shortDescription: "Step-by-step VPN setup and configuration guide — secure browsing, location privacy, and encrypted connection setup.",
    category: "Cybersecurity Software",
    price: 19.99,
    originalPrice: 29.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "pink",
  },
  {
    id: "gem-secure-email-kit",
    sku: "GEM-CS-032",
    name: "GEM Secure Email Setup Kit",
    shortDescription: "Secure email configuration kit — encrypted email setup, spam filtering, phishing protection, and domain authentication.",
    category: "Cybersecurity Software",
    price: 24.99,
    originalPrice: 34.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix", "facebook"],
    accent: "pink",
  },
  {
    id: "gem-cloud-storage-encryption",
    sku: "GEM-CS-033",
    name: "GEM Cloud Storage Encryption Tool",
    shortDescription: "Cloud storage encryption software — end-to-end encryption for Google Drive, Dropbox, and OneDrive files.",
    category: "Cybersecurity Software",
    price: 34.99,
    originalPrice: 49.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "pink",
  },
  {
    id: "gem-browser-privacy-shield",
    sku: "GEM-CS-034",
    name: "GEM Browser Privacy Shield",
    shortDescription: "Browser privacy protection tool — tracker blocking, cookie management, fingerprint protection, and secure search defaults.",
    category: "Cybersecurity Software",
    price: 14.99,
    originalPrice: 22.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "pink",
  },
  {
    id: "gem-mobile-lockdown-guide",
    sku: "GEM-CS-035",
    name: "GEM Mobile Device Lockdown Guide",
    shortDescription: "Mobile device security lockdown guide — iOS and Android hardening, app permissions, biometric setup, and remote wipe config.",
    category: "Cybersecurity Software",
    price: 12.99,
    originalPrice: 19.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "tiktok", "google", "wix", "facebook"],
    accent: "pink",
  },
  {
    id: "gem-social-media-privacy-audit",
    sku: "GEM-CS-036",
    name: "GEM Social Media Privacy Audit",
    shortDescription: "Social media privacy audit service — reviews Facebook, Instagram, X, and LinkedIn settings for data exposure and privacy risks.",
    category: "Cybersecurity Software",
    price: 9.99,
    originalPrice: 15.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix", "facebook"],
    accent: "pink",
  },
];

export function getStorefrontDefinition(slug: StorefrontSlug): StorefrontDefinition | undefined {
  return storefrontDefinitions.find((s) => s.slug === slug);
}

export function getProductsForStorefront(slug: StorefrontSlug): StorefrontProduct[] {
  return storefrontProducts.filter((p) => p.storefronts.includes(slug));
}
