export type StorefrontSlug =
  | "main"
  | "campaign-hub"
  | "tiktok"
  | "shopify"
  | "google"
  | "wix";

export type StorefrontProduct = {
  id: string;
  sku: string;
  name: string;
  shortDescription: string;
  category: string;
  price: number;
  originalPrice?: number;
  deliveryType: "Physical" | "Digital" | "Service";
  stockLabel: "In Stock" | "Available" | "Request access";
  storefronts: StorefrontSlug[];
  accent: "cyan" | "green" | "purple" | "orange" | "pink";
  image?: string;
  checkoutUrl?: string;
};

export type StorefrontDefinition = {
  slug: StorefrontSlug;
  name: string;
  shortName: string;
  eyebrow: string;
  title: string;
  description: string;
  status: "Live" | "Connected" | "Prepared" | "Pending connection";
  externalUrl?: string;
  externalLabel?: string;
  categories: string[];
};

export const storefrontDefinitions: StorefrontDefinition[] = [
  {
    slug: "main",
    name: "GEM Main Store",
    shortName: "Main Store",
    eyebrow: "Professional product catalog",
    title: "The complete GEM Enterprise service and software store",
    description:
      "Browse 36 professional cybersecurity, financial protection, real estate security, and home safety products — all delivered digitally or as managed services.",
    status: "Live",
    categories: [
      "All",
      "Monitoring Plans",
      "Financial Protection",
      "Home Security",
      "Real Estate Services",
      "Cybersecurity Software",
    ],
  },
  {
    slug: "campaign-hub",
    name: "Campaign Hub",
    shortName: "Campaign Hub",
    eyebrow: "Campaign-ready products",
    title: "Campaign-ready security products and digital offers",
    description:
      "A dedicated page for promoted cybersecurity products, awareness tools, and lead-generation services optimized for social campaigns.",
    status: "Connected",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Financial Protection", "Security Awareness"],
  },
  {
    slug: "tiktok",
    name: "TikTok Shop",
    shortName: "TikTok Shop",
    eyebrow: "Social-commerce catalog",
    title: "Products prepared for the GEM TikTok Shop",
    description:
      "Showcase consumer-friendly cybersecurity and real estate security products inside the GEM website before opening the approved external TikTok Shop destination.",
    status: "Pending connection",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Home Security"],
  },
  {
    slug: "shopify",
    name: "Shopify Store",
    shortName: "Shopify",
    eyebrow: "Connected checkout",
    title: "GEM products available through Shopify",
    description:
      "Review the GEM product information first, then continue to the approved Shopify checkout where a live destination exists.",
    status: "Connected",
    externalUrl: "https://my-store-8c2jeowo.myshopify.com/products/24-7-threat-monitoring-service",
    externalLabel: "Open Shopify checkout",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software"],
  },
  {
    slug: "google",
    name: "Google Merchant Store",
    shortName: "Google Store",
    eyebrow: "Merchant feed catalog",
    title: "Google-ready product listings and destinations",
    description:
      "A dedicated catalog view for products prepared for Google Merchant Center, product feeds, and shopping visibility.",
    status: "Prepared",
    categories: ["All", "Monitoring Plans", "Cybersecurity Software", "Real Estate Services", "Home Security"],
  },
  {
    slug: "wix",
    name: "Wix Store Sync",
    shortName: "Wix Store",
    eyebrow: "Synchronized catalog",
    title: "Wix-origin products mapped into GEM Enterprise",
    description:
      "All 36 professional products synchronized from the Wix operational hub — cybersecurity monitoring, financial protection, home security, real estate services, and cybersecurity software.",
    status: "Connected",
    categories: ["All", "Monitoring Plans", "Financial Protection", "Home Security", "Real Estate Services", "Cybersecurity Software"],
  },
];

// Image URLs from generated branded product cards
const IMG = {
  familyProtection: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/50068119f_generated_image.png",
  enterpriseShield: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/af1e3f484_generated_image.png",
  businessMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/0fcfdbdd1_generated_image.png",
  proMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/fa5a68144_generated_image.png",
  basicMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7b1af6854_generated_image.png",
  creditFreeze: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/f01c388d9_generated_image.png",
  fraudMasterclass: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/1a8d2dd66_generated_image.png",
  becProtection: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/9e9dbd58c_generated_image.png",
  cryptoWallet: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/67a2937eb_generated_image.png",
  identityShield: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7d770947e_generated_image.png",
  cyberInsurance: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/c64318ce2_generated_image.png",
  identityTheft: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/0d0d9f9bc_generated_image.png",
  familySafety: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/2624cb60b_generated_image.png",
  wifiHardening: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7fdba25db_generated_image.png",
  smartHome: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/697f0c794_generated_image.png",
  homeBuyerFraud: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/abcc3e97d_generated_image.png",
  rentalManagement: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/32d524d6f_generated_image.png",
  investmentConsult: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/644a6e594_generated_image.png",
  dueDiligence: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/a89e712c7_generated_image.png",
  titleFraud: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/cc2e1ee62_generated_image.png",
  darkwebMonitor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/0b866cf74_generated_image.png",
  endpointArmor: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/d5cdc44f9_generated_image.png",
  phishGuard: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/cdfb8e1af_generated_image.png",
  vaultSafe: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/7f34b96c6_generated_image.png",
  threatShield: "https://media.base44.com/images/public/69d42975b7b1794c3dc01661/83a890ee0_generated_image.png",
};

export const storefrontProducts: StorefrontProduct[] = [
  // ====== MONITORING PLANS (6) ======
  {
    id: "gem-family-protection",
    sku: "GEM-MP-001",
    name: "GEM Family Protection Plan",
    shortDescription: "Comprehensive family cybersecurity monitoring — dark web scanning, phishing alerts, and identity protection for one household.",
    category: "Monitoring Plans",
    price: 9.99,
    originalPrice: 14.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "cyan",
    image: IMG.familyProtection,
  },
  {
    id: "gem-enterprise-shield",
    sku: "GEM-MP-002",
    name: "GEM Enterprise Shield — Annual",
    shortDescription: "Enterprise-grade 24/7 SOC monitoring, incident response, and threat intelligence for organizations. Annual prepaid subscription.",
    category: "Monitoring Plans",
    price: 799,
    originalPrice: 999,
    deliveryType: "Service",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "cyan",
    image: IMG.enterpriseShield,
  },
  {
    id: "gem-business-monitor",
    sku: "GEM-MP-003",
    name: "GEM Business Monitor — Monthly",
    shortDescription: "Business-grade continuous monitoring with threat alerts, vulnerability scanning, and compliance reporting.",
    category: "Monitoring Plans",
    price: 49,
    originalPrice: 65,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "cyan",
    image: IMG.businessMonitor,
  },
  {
    id: "gem-pro-monitor",
    sku: "GEM-MP-004",
    name: "GEM Pro Monitor — Monthly",
    shortDescription: "Professional-tier monitoring with advanced threat detection, dark web surveillance, and priority alert delivery.",
    category: "Monitoring Plans",
    price: 19.99,
    originalPrice: 29.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix"],
    accent: "cyan",
    image: IMG.proMonitor,
  },
  {
    id: "gem-basic-monitor",
    sku: "GEM-MP-005",
    name: "GEM Basic Monitor — Monthly",
    shortDescription: "Entry-level cybersecurity monitoring with weekly threat summaries and basic dark web exposure checks.",
    category: "Monitoring Plans",
    price: 9.99,
    originalPrice: 14.99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix"],
    accent: "cyan",
    image: IMG.basicMonitor,
  },
  {
    id: "gem-threat-alert-sms",
    sku: "GEM-MP-006",
    name: "GEM Basic Threat Alert SMS",
    shortDescription: "Real-time SMS security alerts for defined business and personal monitoring needs. Immediate notification on critical threats.",
    category: "Monitoring Plans",
    price: 10,
    originalPrice: 15,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "cyan",
  },

  // ====== FINANCIAL PROTECTION (5) ======
  {
    id: "credit-freeze-guide",
    sku: "GEM-FP-001",
    name: "Credit Freeze & Recovery Guide",
    shortDescription: "Step-by-step guide to freezing credit across all three bureaus and recovering from identity theft incidents.",
    category: "Financial Protection",
    price: 24.99,
    originalPrice: 34.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "green",
    image: IMG.creditFreeze,
  },
  {
    id: "fraud-prevention-masterclass",
    sku: "GEM-FP-002",
    name: "Fraud Prevention Masterclass",
    shortDescription: "Comprehensive video course covering business email compromise, wire fraud, social engineering, and financial fraud prevention.",
    category: "Financial Protection",
    price: 199,
    originalPrice: 299,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "green",
    image: IMG.fraudMasterclass,
  },
  {
    id: "bec-protection",
    sku: "GEM-FP-003",
    name: "Business Email Compromise Protection",
    shortDescription: "Email security audit and configuration service to prevent BEC attacks, spoofing, and phishing targeting business finances.",
    category: "Financial Protection",
    price: 99,
    originalPrice: 149,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "green",
    image: IMG.becProtection,
  },
  {
    id: "crypto-wallet-audit",
    sku: "GEM-FP-004",
    name: "Crypto Wallet Security Audit",
    shortDescription: "Professional security audit of cryptocurrency wallets, exchange accounts, and DeFi positions with remediation recommendations.",
    category: "Financial Protection",
    price: 149,
    originalPrice: 199,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "green",
    image: IMG.cryptoWallet,
  },
  {
    id: "financial-identity-shield",
    sku: "GEM-FP-005",
    name: "Financial Identity Shield",
    shortDescription: "Identity protection toolkit with account monitoring, fraud alerts, and personal data exposure assessment for financial accounts.",
    category: "Financial Protection",
    price: 39.99,
    originalPrice: 59.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "green",
    image: IMG.identityShield,
  },

  // ====== HOME SECURITY (5) ======
  {
    id: "cyber-insurance-readiness",
    sku: "GEM-HS-001",
    name: "Home Cyber Insurance Readiness Report",
    shortDescription: "Documented readiness review to help households understand cyber-insurance preparation gaps and qualify for coverage.",
    category: "Home Security",
    price: 49,
    originalPrice: 69,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "purple",
    image: IMG.cyberInsurance,
  },
  {
    id: "identity-theft-recovery",
    sku: "GEM-HS-002",
    name: "Identity Theft Recovery Kit",
    shortDescription: "Complete recovery kit with templates, contact lists, and step-by-step procedures for restoring a stolen identity.",
    category: "Home Security",
    price: 29,
    originalPrice: 39,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "purple",
    image: IMG.identityTheft,
  },
  {
    id: "family-digital-safety",
    sku: "GEM-HS-003",
    name: "Family Digital Safety Plan",
    shortDescription: "Comprehensive digital safety plan covering parental controls, device security, social media privacy, and online behavior guidelines.",
    category: "Home Security",
    price: 19.99,
    originalPrice: 29.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix"],
    accent: "purple",
    image: IMG.familySafety,
  },
  {
    id: "wifi-hardening-guide",
    sku: "GEM-HS-004",
    name: "WiFi Network Hardening Guide",
    shortDescription: "Technical guide to securing home WiFi networks — encryption setup, guest network isolation, IoT device protection, and intrusion detection.",
    category: "Home Security",
    price: 29,
    originalPrice: 39,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "purple",
    image: IMG.wifiHardening,
  },
  {
    id: "smart-home-audit",
    sku: "GEM-HS-005",
    name: "Smart Home Security Audit",
    shortDescription: "Professional audit of smart home devices, IoT vulnerabilities, voice assistant privacy, and automated security configuration.",
    category: "Home Security",
    price: 99,
    originalPrice: 149,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "purple",
    image: IMG.smartHome,
  },

  // ====== REAL ESTATE SERVICES (6) ======
  {
    id: "home-buyer-fraud-alert",
    sku: "GEM-RE-001",
    name: "Home Buyer Fraud Alert Package",
    shortDescription: "Protection package for home buyers — wire fraud prevention, title verification, and real estate scam awareness training.",
    category: "Real Estate Services",
    price: 199,
    originalPrice: 299,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.homeBuyerFraud,
  },
  {
    id: "rental-management-kit",
    sku: "GEM-RE-002",
    name: "Rental Property Management Starter Kit",
    shortDescription: "Complete starter kit for rental property owners — lease templates, tenant screening procedures, and cybersecurity best practices.",
    category: "Real Estate Services",
    price: 89,
    originalPrice: 129,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.rentalManagement,
  },
  {
    id: "investment-consultation",
    sku: "GEM-RE-003",
    name: "Investment Property Consultation",
    shortDescription: "One-on-one consultation on investment property cybersecurity, smart security integration, and digital asset protection strategies.",
    category: "Real Estate Services",
    price: 299,
    originalPrice: 399,
    deliveryType: "Service",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.investmentConsult,
  },
  {
    id: "due-diligence-report",
    sku: "GEM-RE-004",
    name: "Real Estate Due Diligence Report",
    shortDescription: "Comprehensive due diligence report covering property cybersecurity risks, smart device audit, and digital security recommendations.",
    category: "Real Estate Services",
    price: 149,
    originalPrice: 199,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.dueDiligence,
  },
  {
    id: "title-fraud-protection",
    sku: "GEM-RE-005",
    name: "Property Title Fraud Protection",
    shortDescription: "Active monitoring service that alerts you to unauthorized title transfers, deed changes, and lien filings on your property.",
    category: "Real Estate Services",
    price: 99,
    originalPrice: 149,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
    image: IMG.titleFraud,
  },
  {
    id: "lease-agreement-review",
    sku: "GEM-RE-006",
    name: "Alliance Trust — Lease Agreement Review",
    shortDescription: "Structured legal-cybersecurity review of lease documents, digital clause risks, and property-related agreement preparation.",
    category: "Real Estate Services",
    price: 45,
    originalPrice: 59,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },

  // ====== CYBERSECURITY SOFTWARE (5) ======
  {
    id: "gem-darkweb-monitor",
    sku: "GEM-CS-001",
    name: "GEM DarkWeb Monitor",
    shortDescription: "Continuous dark web surveillance — monitors credential dumps, data breaches, and underground marketplaces for your exposed information.",
    category: "Cybersecurity Software",
    price: 79.99,
    originalPrice: 99.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "shopify", "google", "wix"],
    accent: "pink",
    image: IMG.darkwebMonitor,
  },
  {
    id: "gem-endpoint-armor",
    sku: "GEM-CS-002",
    name: "GEM EndpointArmor Suite",
    shortDescription: "Enterprise endpoint protection — antivirus, EDR, device hardening, and real-time threat response for laptops, servers, and mobile devices.",
    category: "Cybersecurity Software",
    price: 69.99,
    originalPrice: 89.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "shopify", "google", "wix"],
    accent: "pink",
    image: IMG.endpointArmor,
  },
  {
    id: "gem-phishguard",
    sku: "GEM-CS-003",
    name: "GEM PhishGuard Email Filter",
    shortDescription: "AI-powered email filtering that blocks phishing, BEC, and social engineering attacks before they reach the inbox.",
    category: "Cybersecurity Software",
    price: 29.99,
    originalPrice: 39.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "shopify", "google", "wix"],
    accent: "pink",
    image: IMG.phishGuard,
  },
  {
    id: "gem-vaultsafe",
    sku: "GEM-CS-004",
    name: "GEM VaultSafe Password Manager",
    shortDescription: "Secure password vault with breach monitoring, password strength analysis, and cross-device sync with zero-knowledge encryption.",
    category: "Cybersecurity Software",
    price: 19.99,
    originalPrice: 29.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "shopify", "google", "wix"],
    accent: "pink",
    image: IMG.vaultSafe,
  },
  {
    id: "gem-threat-shield-pro",
    sku: "GEM-CS-005",
    name: "GEM Threat Shield Pro",
    shortDescription: "Advanced threat protection suite — network defense, intrusion prevention, malware blocking, and real-time security analytics dashboard.",
    category: "Cybersecurity Software",
    price: 59.99,
    originalPrice: 79.99,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "shopify", "google", "wix"],
    accent: "pink",
    image: IMG.threatShield,
  },

  // ====== SECURITY AWARENESS & COMPLIANCE (5) ======
  {
    id: "gem-starter-bundle",
    sku: "GEM-SA-001",
    name: "GEM Starter Security Bundle",
    shortDescription: "Essential cybersecurity starter pack — password vault, phishing alerts, and dark web scan for one user. Perfect entry point.",
    category: "Cybersecurity Software",
    price: 20,
    originalPrice: 35,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix"],
    accent: "cyan",
  },
  {
    id: "phishing-awareness-report",
    sku: "GEM-SA-002",
    name: "GEM Phishing Test & Awareness Report",
    shortDescription: "Simulated phishing campaign with detailed report — identifies vulnerable users and provides remediation training recommendations.",
    category: "Cybersecurity Software",
    price: 15,
    originalPrice: 25,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "cyan",
  },
  {
    id: "weekly-threat-digest",
    sku: "GEM-SA-003",
    name: "GEM Weekly Threat Digest — Newsletter",
    shortDescription: "Weekly curated intelligence briefing covering emerging threats, vulnerability alerts, and actionable security recommendations.",
    category: "Cybersecurity Software",
    price: 5,
    originalPrice: 9,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "cyan",
  },
  {
    id: "social-media-protection",
    sku: "GEM-SA-004",
    name: "GEM Social Media Account Protection Kit",
    shortDescription: "Complete kit for securing social media accounts — 2FA setup, privacy configuration, impersonation monitoring, and recovery procedures.",
    category: "Cybersecurity Software",
    price: 35,
    originalPrice: 49,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "tiktok", "google", "wix"],
    accent: "cyan",
  },
  {
    id: "twofa-setup-guide",
    sku: "GEM-SA-005",
    name: "GEM Two-Factor Authentication Setup Guide",
    shortDescription: "Comprehensive guide to deploying 2FA across all business and personal accounts — app-based, hardware keys, and backup codes.",
    category: "Cybersecurity Software",
    price: 15,
    originalPrice: 25,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "cyan",
  },

  // ====== ALLIANCE TRUST REAL ESTATE SERVICES (5) ======
  {
    id: "commercial-property-risk",
    sku: "GEM-AT-001",
    name: "Alliance Trust — Commercial Property Risk Report",
    shortDescription: "Structured commercial property risk assessment covering cybersecurity vulnerabilities, physical security gaps, and compliance exposure.",
    category: "Real Estate Services",
    price: 130,
    originalPrice: 175,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "tenant-screening-package",
    sku: "GEM-AT-002",
    name: "Alliance Trust — Tenant Screening Package",
    shortDescription: "Comprehensive tenant screening with background checks, financial verification, and digital identity validation for property owners.",
    category: "Real Estate Services",
    price: 75,
    originalPrice: 99,
    deliveryType: "Service",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "property-valuation-report",
    sku: "GEM-AT-003",
    name: "Alliance Trust — Property Valuation Report",
    shortDescription: "Professional property valuation with digital risk assessment, market analysis, and cybersecurity infrastructure review.",
    category: "Real Estate Services",
    price: 95,
    originalPrice: 129,
    deliveryType: "Digital",
    stockLabel: "Available",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "investment-portfolio-review",
    sku: "GEM-AT-004",
    name: "Alliance Trust — Investment Portfolio Review",
    shortDescription: "One-on-one review of real estate investment portfolio — risk analysis, cybersecurity exposure, and digital asset protection strategy.",
    category: "Real Estate Services",
    price: 250,
    originalPrice: 350,
    deliveryType: "Service",
    stockLabel: "Request access",
    storefronts: ["main", "google", "wix"],
    accent: "orange",
  },
  {
    id: "compliance-vault",
    sku: "GEM-SA-006",
    name: "GEM Compliance Vault",
    shortDescription: "Structured digital workspace for organizing compliance documents, evidence, audit trails, and review priorities with secure access controls.",
    category: "Cybersecurity Software",
    price: 499,
    deliveryType: "Digital",
    stockLabel: "Request access",
    storefronts: ["main", "campaign-hub", "google", "wix"],
    accent: "purple",
  },
];

export function getStorefrontDefinition(slug: StorefrontSlug) {
  return storefrontDefinitions.find((storefront) => storefront.slug === slug);
}

export function getProductsForStorefront(slug: StorefrontSlug) {
  return storefrontProducts.filter((product) => product.storefronts.includes(slug));
}
