export type GovernedIntegrationReadiness =
  | "READY"
  | "PARTIAL"
  | "HUMAN_REQUIRED"
  | "BLOCKED";

export interface GovernedIntegrationDefinition {
  slug: string;
  title: string;
  category: string;
  description: string;
  status: string;
  readiness: GovernedIntegrationReadiness;
  operationalHref: string;
  capabilities: readonly string[];
  activationRequirements: readonly string[];
}

export const governedIntegrationCatalog: readonly GovernedIntegrationDefinition[] = [
  {
    slug: "github",
    title: "GitHub",
    category: "Development & delivery",
    description: "Repository, branch, pull-request, review, workflow, and release evidence for governed development work.",
    status: "Authorization remains in the approved GitHub installation",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/development",
    capabilities: ["Source control", "Pull-request governance", "CI evidence", "Release traceability"],
    activationRequirements: ["Approved GitHub installation", "Repository-level access", "Protected-branch policy"],
  },
  {
    slug: "vercel",
    title: "Vercel",
    category: "Development & delivery",
    description: "Canonical preview and production delivery for the GEM Next.js application.",
    status: "Production delivery remains Git-integration controlled",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/development",
    capabilities: ["Preview deployments", "Production deployment", "Build evidence", "Domain routing"],
    activationRequirements: ["Authorized Vercel project", "Git integration", "Verified production domains"],
  },
  {
    slug: "cloudflare",
    title: "Cloudflare",
    category: "Infrastructure",
    description: "DNS, edge security, Workers, storage, and operational health for approved GEM services.",
    status: "Account authorization and resource health are verified separately",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/monitoring",
    capabilities: ["DNS", "Edge security", "Workers", "D1, R2, KV, and Durable Objects"],
    activationRequirements: ["Authorized account", "Resource-scoped credentials", "Health and rollback evidence"],
  },
  {
    slug: "supabase",
    title: "Supabase",
    category: "Data & identity",
    description: "Workspace data, identity gateway, private storage, and backend operations.",
    status: "Database, identity, and storage readiness remain independently gated",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/monitoring",
    capabilities: ["PostgreSQL", "Authentication gateway", "Private storage", "Workspace operations"],
    activationRequirements: ["Verified project", "Server-only credentials", "Schema and storage acceptance"],
  },
  {
    slug: "openai",
    title: "OpenAI",
    category: "AI & agents",
    description: "Governed assistance and agent workflows with human escalation and restricted action boundaries.",
    status: "AI operations remain policy, credential, and approval scoped",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/ai-services",
    capabilities: ["AI assistance", "Agent orchestration", "Structured output", "Human escalation"],
    activationRequirements: ["Approved model access", "Server-side credentials", "Audit and approval policy"],
  },
  {
    slug: "hugging-face",
    title: "Hugging Face",
    category: "AI & agents",
    description: "Model, dataset, and inference integration surface for approved GEM workloads.",
    status: "Model and inference authorization required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/ai-services",
    capabilities: ["Model registry", "Inference", "Datasets", "Evaluation workflows"],
    activationRequirements: ["Approved organization access", "Model license review", "Scoped inference credential"],
  },
  {
    slug: "base44",
    title: "Base44",
    category: "AI & agents",
    description: "Connected application-development surface for approved GEM prototypes and operational apps.",
    status: "Application ownership and environment mapping required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/development",
    capabilities: ["Application development", "Workspace mapping", "Operational prototypes", "Service handoff"],
    activationRequirements: ["Authorized workspace", "Application ownership", "Production handoff review"],
  },
  {
    slug: "pinokio",
    title: "Pinokio",
    category: "AI & media",
    description: "Owner-controlled Windows launcher for local ComfyUI and approved media applications.",
    status: "Requires the healthy Windows media host",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/social-media/video",
    capabilities: ["Local app lifecycle", "ComfyUI launch", "Media runtime isolation", "Host recovery"],
    activationRequirements: ["Owner-controlled Windows host", "Local application acceptance", "Private network boundary"],
  },
  {
    slug: "comfyui",
    title: "ComfyUI",
    category: "AI & media",
    description: "Private AI-video generation through the trusted GEM Windows render worker.",
    status: "Requires a healthy local renderer and approved workflow",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/social-media/video",
    capabilities: ["Workflow rendering", "Video generation", "Private output", "Version-bound return"],
    activationRequirements: ["Local API health", "Approved API-format workflow", "Trusted worker callback verification"],
  },
  {
    slug: "obs",
    title: "OBS Studio",
    category: "AI & media",
    description: "Live-video composition and Virtual Camera bridge for GEM call and showcase workflows.",
    status: "Requires local OBS, WebSocket, camera, and device acceptance",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/social-media/video",
    capabilities: ["Scene composition", "Virtual Camera", "WebSocket control", "Media playback"],
    activationRequirements: ["OBS WebSocket health", "Virtual Camera acceptance", "Camera and microphone permission"],
  },
  {
    slug: "decart",
    title: "Decart Live Studio",
    category: "AI & media",
    description: "Realtime AI-video transformation for approved GEM call-studio workflows.",
    status: "Local provider authorization and Windows acceptance required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/meetings",
    capabilities: ["Realtime transformation", "Call-studio input", "OBS composition", "Local credential isolation"],
    activationRequirements: ["Approved Decart account", "Local secret entry", "Camera and end-to-end call acceptance"],
  },
  {
    slug: "google-workspace",
    title: "Google Workspace",
    category: "Productivity",
    description: "Governed Drive, Gmail, Calendar, Docs, Sheets, and Slides collaboration entry point.",
    status: "Workspace OAuth and service-specific scopes required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/documents",
    capabilities: ["Drive files", "Gmail workflows", "Calendar scheduling", "Docs, Sheets, and Slides"],
    activationRequirements: ["Authorized Google Workspace", "Least-privilege OAuth scopes", "Workspace data policy"],
  },
  {
    slug: "zoom",
    title: "Zoom",
    category: "Communications",
    description: "Meeting, webinar, video SDK, team chat, and event integration for approved GEM sessions.",
    status: "Zoom app authorization and webhook validation required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/meetings",
    capabilities: ["Meetings", "Webinars", "Video SDK", "Webhooks"],
    activationRequirements: ["Approved Zoom app", "OAuth scopes", "Webhook signature verification"],
  },
  {
    slug: "hubspot",
    title: "HubSpot",
    category: "CRM & growth",
    description: "CRM, customer preparation, pipeline health, and governed commercial handoffs.",
    status: "Portal authorization and CRM mapping required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/sales",
    capabilities: ["CRM records", "Pipeline health", "Customer preparation", "Handoff workflows"],
    activationRequirements: ["Authorized HubSpot portal", "Object and property mapping", "Write approval policy"],
  },
  {
    slug: "stripe",
    title: "Stripe",
    category: "Commerce",
    description: "Billing, subscriptions, usage, payment events, and financial reconciliation controls.",
    status: "Billing and webhook activation remain disabled until approved",
    readiness: "BLOCKED",
    operationalHref: "/app/command-center/revenue",
    capabilities: ["Billing", "Subscriptions", "Usage metering", "Webhook reconciliation"],
    activationRequirements: ["Approved Stripe account", "Verified webhook endpoint", "Product and price approval"],
  },
  {
    slug: "figma",
    title: "Figma",
    category: "Design",
    description: "Design files, component libraries, diagrams, and design-to-code handoff.",
    status: "Team and file authorization required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/development",
    capabilities: ["Design files", "Component libraries", "Diagrams", "Code Connect"],
    activationRequirements: ["Authorized Figma team", "File access", "Design-system ownership"],
  },
  {
    slug: "notion",
    title: "Notion",
    category: "Knowledge",
    description: "Governed knowledge capture, research documentation, meetings, and implementation specifications.",
    status: "Workspace authorization and page scope required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/documents",
    capabilities: ["Knowledge capture", "Meeting intelligence", "Research documentation", "Specifications"],
    activationRequirements: ["Authorized Notion workspace", "Page scope", "Knowledge ownership policy"],
  },
  {
    slug: "posthog",
    title: "PostHog",
    category: "Analytics",
    description: "Product analytics, funnels, feature usage, and controlled diagnostic evidence.",
    status: "Project authorization and privacy review required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/command-center/monitoring",
    capabilities: ["Product analytics", "Funnels", "Feature usage", "Diagnostics"],
    activationRequirements: ["Authorized project", "Event taxonomy", "Privacy and retention review"],
  },
  {
    slug: "dropbox",
    title: "Dropbox",
    category: "Storage & content",
    description: "File discovery, collection, inspection, organization, and sharing for approved content.",
    status: "Dropbox authorization and folder scope required",
    readiness: "HUMAN_REQUIRED",
    operationalHref: "/app/documents",
    capabilities: ["File discovery", "Collections", "Organization", "Controlled sharing"],
    activationRequirements: ["Authorized Dropbox account", "Folder scope", "Sharing and retention policy"],
  },
] as const;

export function governedIntegrationBySlug(slug: string) {
  return governedIntegrationCatalog.find((integration) => integration.slug === slug);
}
