import { redirect } from "next/navigation";
import { Building2, CalendarDays, CheckCircle2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { requirePlatformOwner } from "@/lib/api/auth-helpers";
import { db } from "@/lib/db";

export const dynamic="force-dynamic";
export const metadata={title:"Organization Highlights | GEM Enterprise"};
export default async function OrganizationReportsPage(){
  const gate=await requirePlatformOwner();if(!gate.ok)redirect(gate.response.status===401?"/client-login?next=/app/admin/organization-reports":"/app/admin?ownerAccess=required");
  const updates=await db.workspaceWeeklyUpdate.findMany({where:{status:"APPROVED"},orderBy:{weekEnding:"desc"},take:100,include:{workspace:{include:{organization:true}},project:{select:{name:true}},author:{select:{email:true,profile:{select:{displayName:true}}}},reviewer:{select:{email:true,profile:{select:{displayName:true}}}}}});
  return <div className="space-y-6 pb-12"><section className="rounded-2xl border border-cyan-400/20 bg-card p-6"><Badge className="bg-cyan-400/10 text-cyan-200"><Building2 className="mr-2 h-4 w-4"/>GEM oversight</Badge><h1 className="mt-4 text-3xl font-bold text-white">Approved organization highlights</h1><p className="mt-2 text-sm text-slate-400">Only workspace-reviewed weekly summaries appear here. Drafts, returned updates, and private workspace records remain outside this platform-owner view.</p></section>{updates.length?<div className="grid gap-5 xl:grid-cols-2">{updates.map(update=><Card key={update.id} className="border-white/10 bg-card"><CardHeader><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-cyan-300">{update.workspace.organization.name}</p><CardTitle className="mt-2 text-lg text-white">{update.project?.name??update.workspace.name}</CardTitle></div><Badge className="bg-emerald-400/10 text-emerald-300"><CheckCircle2 className="mr-1 h-3 w-3"/>Approved</Badge></div></CardHeader><CardContent className="space-y-4 text-sm"><p className="flex items-center gap-2 text-slate-400"><CalendarDays className="h-4 w-4"/>Week ending {update.weekEnding.toLocaleDateString()}</p><div><p className="font-medium text-white">Accomplishments</p><p className="mt-1 whitespace-pre-wrap text-slate-400">{update.accomplishments}</p></div><div><p className="font-medium text-white">In progress</p><p className="mt-1 whitespace-pre-wrap text-slate-400">{update.inProgress}</p></div>{update.blockers&&<div><p className="font-medium text-white">Blockers</p><p className="mt-1 whitespace-pre-wrap text-slate-400">{update.blockers}</p></div>}{update.decisionsNeeded&&<div><p className="font-medium text-white">Decisions needed</p><p className="mt-1 whitespace-pre-wrap text-slate-400">{update.decisionsNeeded}</p></div>}<div><p className="font-medium text-white">Next priorities</p><p className="mt-1 whitespace-pre-wrap text-slate-400">{update.nextPriorities}</p></div></CardContent></Card>)}</div>:<Card className="border-dashed border-white/15 bg-card"><CardContent className="p-8 text-sm text-slate-400">No organization-approved weekly highlight has been forwarded yet.</CardContent></Card>}</div>
}
