import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.49.8";
const u=Deno.env.get("SUPABASE_URL")??"",s=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",a=Deno.env.get("SUPABASE_ANON_KEY")??"";
if(!u||!s||!a)throw new Error("Missing runtime configuration");
const db=createClient(u,s,{auth:{persistSession:false,autoRefreshToken:false}}),rx=/^[A-Za-z0-9_-]{8,128}$/;
class E extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});
const rec=(v:unknown):Record<string,unknown>=>v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:{};
const id=(v:unknown,n:string)=>{if(typeof v!=="string"||!rx.test(v))throw new E(400,"INVALID_IDENTIFIER",`${n} is invalid`);return v};
async function admin(token:unknown){const r=await fetch(`${u}/functions/v1/gem-admin-read`,{method:"POST",headers:{Authorization:`Bearer ${a}`,apikey:a,"Content-Type":"application/json"},body:JSON.stringify({action:"pilot_readiness",token})});if(!r.ok){const b=await r.json().catch(()=>({})) as Record<string,unknown>;throw new E(r.status,typeof b.code==="string"?b.code:"UNAUTHORIZED",typeof b.error==="string"?b.error:"Administrator access required")}}
async function account(x:string){const r=await db.from("users").select("id,role,status,isActive,isEmailVerified").eq("id",x).maybeSingle();if(r.error)throw new E(503,"DATABASE_ERROR",r.error.message);return r.data?{id:String(r.data.id),role:String(r.data.role),status:String(r.data.status),isActive:r.data.isActive===true,isEmailVerified:r.data.isEmailVerified===true}:null}
const meta=(v:unknown)=>{const q=rec(v),r:Record<string,string>={};for(const k of ["stage","reviewAction","previousRole","newRole"])if(typeof q[k]==="string")r[k]=q[k] as string;return r};
async function read(b:Record<string,unknown>){const appId=id(b.applicationId,"Application ID"),analystId=id(b.analystId,"Analyst ID");const [ar,analyst]=await Promise.all([db.from("kyc_applications").select("id,userId,status,reviewerId,formData,submittedAt,reviewedAt,completedAt").eq("id",appId).maybeSingle(),account(analystId)]);if(ar.error)throw new E(503,"DATABASE_ERROR",ar.error.message);if(!ar.data)throw new E(404,"APPLICATION_NOT_FOUND","Verification application not found");if(!analyst)throw new E(404,"ANALYST_NOT_FOUND","Analyst account not found");const app=ar.data as Record<string,unknown>,applicantId=id(app.userId,"Applicant ID");const [applicant,d,rv,dc]=await Promise.all([account(applicantId),db.from("decisions").select("decision,decisionBy,decisionAt").eq("applicationId",appId).maybeSingle(),db.from("kyc_reviews").select("id,reviewerId,action,createdAt").eq("applicationId",appId).order("createdAt"),db.from("kyc_documents").select("id",{count:"exact",head:true}).eq("applicationId",appId)]);for(const x of [d,rv,dc])if(x.error)throw new E(503,"DATABASE_ERROR",x.error.message);if(!applicant)throw new E(404,"APPLICANT_NOT_FOUND","Applicant account not found");const decision=d.data as Record<string,unknown>|null,dm=decision?.decisionBy?await account(id(decision.decisionBy,"Decision-maker ID")):null,ids=[applicantId,analystId,dm?.id].filter((x):x is string=>Boolean(x)),f="action,resource,resourceId,userId,metadata,createdAt";const [aa,ra,la]=await Promise.all([db.from("audit_logs").select(f).eq("resource","verification_application").eq("resourceId",appId).order("createdAt"),db.from("audit_logs").select(f).eq("action","role_change").eq("resource","user").eq("resourceId",analystId).order("createdAt"),db.from("audit_logs").select(f).eq("action","login").in("resource",["auth","user"]).in("resourceId",ids).order("createdAt")]);for(const x of [aa,ra,la])if(x.error)throw new E(503,"DATABASE_ERROR",x.error.message);const m=rec(rec(app.formData)._verificationPilot),audits=[...(aa.data??[]),...(ra.data??[]),...(la.data??[])].map(x=>({action:x.action,resource:x.action==="login"?"user":x.resource,resourceId:x.resourceId,userId:x.userId,metadata:meta(x.metadata),createdAt:x.createdAt})).sort((x,y)=>new Date(x.createdAt).getTime()-new Date(y.createdAt).getTime());return{application:{id:String(app.id),userId:applicantId,status:String(app.status??""),reviewerId:typeof app.reviewerId==="string"?app.reviewerId:null,formData:{_verificationPilot:{synthetic:m.synthetic===true,scenario:typeof m.scenario==="string"?m.scenario:null,version:typeof m.version==="number"?m.version:null}},submittedAt:app.submittedAt??null,reviewedAt:app.reviewedAt??null,completedAt:app.completedAt??null,reviews:rv.data??[],decision:decision?{decision:String(decision.decision??""),decisionBy:String(decision.decisionBy??""),decisionAt:decision.decisionAt}:null,documentCount:dc.count??0},applicant,analyst,decisionMaker:dm,audits}}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Method not allowed",code:"METHOD_NOT_ALLOWED"},405);try{const b=await req.json() as Record<string,unknown>;await admin(b.token);return out(await read(b))}catch(e){if(e instanceof E)return out({error:e.message,code:e.code},e.status);console.error(e);return out({error:"Internal gateway error",code:"INTERNAL_ERROR"},500)}});
