import type { Metadata } from "next";
export const metadata: Metadata = { title: "Cookie Policy", description: "GEM Enterprise cookie categories, purposes, and consent choices." };
const rows = [
  ["Essential", "Authentication, session security, load balancing, and form integrity.", "Required; cannot be disabled."],
  ["Security", "Abuse prevention, audit evidence, fraud detection, and protected-client access controls.", "Required for secured services."],
  ["Preferences", "Remembering non-sensitive interface choices such as dismissed notices.", "Optional where implemented."],
  ["Analytics", "Aggregate site performance and usage measurement through Vercel analytics when enabled.", "Optional/non-essential; deploy only where consent is honored."],
];
export default function CookiePolicyPage(){return <section className="mx-auto max-w-4xl px-4 py-20"><p className="text-xs uppercase tracking-[0.25em] text-cyan-300">Legal</p><h1 className="mt-3 text-4xl font-bold">Cookie Policy</h1><p className="mt-5 text-slate-300">GEM Enterprise uses limited cookies and similar technologies to operate a secure, KYC-gated platform. We do not use cookies to sell personal information.</p><div className="mt-10 overflow-hidden rounded-2xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/10 text-white"><tr><th className="p-4">Category</th><th className="p-4">Purpose</th><th className="p-4">Consent</th></tr></thead><tbody>{rows.map(([a,b,c])=><tr key={a} className="border-t border-white/10"><td className="p-4 font-semibold text-cyan-200">{a}</td><td className="p-4 text-slate-300">{b}</td><td className="p-4 text-slate-300">{c}</td></tr>)}</tbody></table></div><h2 className="mt-10 text-2xl font-semibold">Consent behavior</h2><p className="mt-3 text-slate-300">Essential and security cookies are set only as needed to provide the site and authenticated portal. If analytics or other non-essential cookies are enabled in a deployment, they must be blocked until the visitor provides consent and must support withdrawal by contacting privacy@gemcybersecurityassist.com or through any consent control presented in the interface.</p><h2 className="mt-10 text-2xl font-semibold">Current session cookie</h2><p className="mt-3 text-slate-300">The authenticated portal uses the <code className="rounded bg-white/10 px-1">gem_session</code> cookie with HttpOnly, Secure in production, and SameSite=Lax settings.</p></section>}
