import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "@supabase/supabase-js";

const url=Deno.env.get("SUPABASE_URL")??"";const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
if(!url||!key)throw new Error("Missing Supabase runtime configuration");
const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const enc=new TextEncoder();const dec=new TextDecoder();
const origin="https://www.gemcybersecurityassist.com";const cors={"Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"authorization, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
class E extends Error{constructor(readonly status:number,readonly code:string,message:string){super(message)}}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store","Referrer-Policy":"no-referrer","X-Content-Type-Options":"nosniff"}});
function decode(value:string){const n=value.replace(/-/g,"+").replace(/_/g,"/");return Uint8Array.from(atob(n.padEnd(Math.ceil(n.length/4)*4,"=")),c=>c.charCodeAt(0))}
async function session(token:unknown){if(typeof token!=="string")throw new E(401,"INVALID_SESSION","Invalid session");const p=token.split(".");if(p.length!==3)throw new E(401,"INVALID_SESSION","Invalid session");const signing=await crypto.subtle.importKey("raw",enc.encode(key),{name:"HMAC",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("HMAC",signing,decode(p[2]),enc.encode(`${p[0]}.${p[1]}`)))throw new E(401,"INVALID_SESSION","Invalid session");const claims=JSON.parse(dec.decode(decode(p[1])));if(claims.iss!=="gem-auth-gateway"||claims.aud!=="gem-enterprise"||!claims.sub||claims.exp<=Date.now()/1000)throw new E(401,"SESSION_EXPIRED","Session expired");const {data:user,error}=await db.from("users").select("id,email,role,status,isActive,sessionVersion").eq("id",claims.sub).maybeSingle();if(error||!user||!user.isActive||user.status!=="active"||user.sessionVersion!==claims.sessionVersion)throw new E(401,"SESSION_REVOKED","Session unavailable");return user}
const required=(v:unknown,n:string,max=5000)=>{if(typeof v!=="string"||!v.trim()||v.length>max)throw new E(400,"INVALID_REQUEST",`${n} is required`);return v.trim()};
const slug=(v:string)=>{const s=v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");if(!s)throw new E(400,"INVALID_SLUG","Valid name required");return s};
async function membership(userId:string,workspaceId:string,permission?:[string,string]){const {data,error}=await db.from("tokmetric_workspace_members").select("id,status,role:tokmetric_roles(id,name,description,permissions:tokmetric_permissions(action,scope)),workspace:tokmetric_workspaces(*,organization:tokmetric_organizations(*))").eq("userId",userId).eq("workspaceId",workspaceId).maybeSingle();if(error||!data||data.status!=="active"||data.workspace?.organization?.status!=="active")throw new E(403,"WORKSPACE_ACCESS_DENIED","Workspace access denied");if(permission&&!data.role?.permissions?.some((p:{action:string;scope:string})=>p.action===permission[0]&&p.scope===permission[1]))throw new E(403,"WORKSPACE_PERMISSION_DENIED","Workspace permission denied");return data}
async function access(userId:string){const {data,error}=await db.from("tokmetric_workspace_members").select("id,status,role:tokmetric_roles(name,description,permissions:tokmetric_permissions(action,scope)),workspace:tokmetric_workspaces(*,organization:tokmetric_organizations(*))").eq("userId",userId).eq("status","active");if(error)throw new E(503,"DATABASE_ERROR",error.message);return (data??[]).filter(m=>m.workspace?.organization?.status==="active").map(m=>({membershipId:m.id,id:m.workspace.id,name:m.workspace.name,slug:m.workspace.slug,organization:{id:m.workspace.organization.id,name:m.workspace.organization.name,slug:m.workspace.organization.slug,billingPlan:m.workspace.organization.billingPlan},role:{name:m.role?.name??"Member",description:m.role?.description??null},permissions:m.role?.permissions??[],counts:{members:0,connectors:0,approvalRecords:0},controls:{globalEmergencyLock:m.workspace.globalEmergencyLock,publishingDisabled:m.workspace.publishingDisabled,advertisingDisabled:m.workspace.advertisingDisabled,shopWriteDisabled:m.workspace.shopWriteDisabled,connectorDisabled:m.workspace.connectorDisabled}}))}
async function overview(userId:string,workspaceId:string){const m=await membership(userId,workspaceId);const [projects,updates,members,roles]=await Promise.all([db.from("organization_projects").select("*").eq("workspaceId",workspaceId).neq("status","ARCHIVED").order("updatedAt",{ascending:false}),db.from("workspace_weekly_updates").select("*,project:organization_projects(id,name),author:users!workspace_weekly_updates_authorUserId_fkey(id,email,user_profiles(displayName))").eq("workspaceId",workspaceId).order("weekEnding",{ascending:false}).limit(12),db.from("tokmetric_workspace_members").select("id,user:users(id,email,user_profiles(displayName)),role:tokmetric_roles(id,name)").eq("workspaceId",workspaceId).eq("status","active"),db.from("tokmetric_roles").select("id,name,description").eq("workspaceId",workspaceId).order("name")]);for(const q of [projects,updates,members,roles])if(q.error)throw new E(503,"DATABASE_ERROR",q.error.message);return{workspace:{id:m.workspace.id,name:m.workspace.name,slug:m.workspace.slug,organization:{id:m.workspace.organization.id,name:m.workspace.organization.name,slug:m.workspace.organization.slug},role:m.role?.name??"Member",permissions:m.role?.permissions??[],status:"ACTIVE",projectSetup:projects.data?.length?"IN_PROGRESS":"NOT_STARTED"},projects:projects.data??[],updates:updates.data??[],members:members.data??[],roles:roles.data??[],viewerUserId:userId,modules:[{id:"projects",label:"Projects",state:"AVAILABLE"},{id:"team",label:"Team",state:"AVAILABLE"},{id:"weekly_updates",label:"Weekly updates",state:"AVAILABLE"},{id:"requests",label:"Service requests",state:"AVAILABLE"},{id:"documents",label:"Documents",state:"SETUP_IN_PROGRESS"},{id:"reports",label:"Reports",state:"SETUP_IN_PROGRESS"},{id:"automations",label:"Automations",state:"NOT_ACTIVATED"},{id:"integrations",label:"Integrations",state:"NOT_ACTIVATED"}]}}
async function audit(userId:string,resource:string,resourceId:string,metadata:Record<string,unknown>){const {error}=await db.from("audit_logs").insert({id:crypto.randomUUID(),userId,action:"admin_action",resource,resourceId,metadata,createdAt:new Date().toISOString()});if(error)throw new E(503,"AUDIT_FAILED","Audit persistence failed")}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const b=await req.json();const u=await session(b.token);const action=b.action;
if(action==="access")return json({workspaces:await access(u.id)});if(action==="overview")return json(await overview(u.id,required(b.workspaceId,"workspaceId",128)));
if(action==="create_project"){const w=required(b.workspaceId,"workspaceId",128);await membership(u.id,w,["manage","projects"]);const name=required(b.name,"name",120),summary=required(b.summary,"summary",2000);const row={id:crypto.randomUUID(),workspaceId:w,name,slug:slug(name),summary,status:["PLANNED","ACTIVE","PAUSED","COMPLETED"].includes(b.status)?b.status:"PLANNED",progress:Number.isInteger(b.progress)&&b.progress>=0&&b.progress<=100?b.progress:0,ownerUserId:u.id,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const {data,error}=await db.from("organization_projects").insert(row).select().single();if(error)throw new E(400,"PROJECT_CREATE_FAILED",error.message);await audit(u.id,"organization_project",data.id,{operation:"project_created",workspaceId:w});return json({project:data},201)}
if(action==="create_update"){const w=required(b.workspaceId,"workspaceId",128);await membership(u.id,w,["manage","weekly_updates"]);const row={id:crypto.randomUUID(),workspaceId:w,projectId:b.projectId||null,authorUserId:u.id,weekEnding:required(b.weekEnding,"weekEnding",20),accomplishments:required(b.accomplishments,"accomplishments"),inProgress:required(b.inProgress,"inProgress"),blockers:typeof b.blockers==="string"?b.blockers:null,decisionsNeeded:typeof b.decisionsNeeded==="string"?b.decisionsNeeded:null,nextPriorities:required(b.nextPriorities,"nextPriorities"),status:b.submit?"SUBMITTED":"DRAFT",submittedAt:b.submit?new Date().toISOString():null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const {data,error}=await db.from("workspace_weekly_updates").insert(row).select().single();if(error)throw new E(400,"UPDATE_CREATE_FAILED",error.message);await audit(u.id,"workspace_weekly_update",data.id,{operation:b.submit?"weekly_update_submitted":"weekly_update_drafted",workspaceId:w});return json({update:data},201)}
throw new E(400,"UNKNOWN_ACTION","Unknown workspace action")}catch(e){if(e instanceof E)return json({error:e.message,code:e.code},e.status);console.error(e);return json({error:"Workspace gateway failed",code:"INTERNAL_ERROR"},500)}});
